[package]
name = "vyon/lagoon-dev"
description = ""
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
license = "MIT"
realm = "shared"
authors = ["Vyon (https://github.com/Vyon)"]

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
